language: go

go:
  - release

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
# - go get golang.org/x/tools/cmd/cover
  - go get code.google.com/p/go.tools/cmd/cover

install:

script:
  - go test -v .
  - $HOME/gopath/bin/goveralls -repotoken 5glf4xLR99hc2ZOsU6s4Jj1TXpE63XxLr

#branches:
#  only:
#    - master

