language: go

go:
  - 1.6.4
  - 1.7.5
  - 1.8
  - tip

sudo: false
cache: bundler

before_install:
  - pip install --user codecov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:

script:
  - go test ./...
  - go test -tags=appengine ./...
  - cd tokenizer; go test -benchmem -bench .; cd ..
  - cd tokenizer; go test -tags=appengine -benchmem -bench .; cd ..
  - cd internal/dic; go test -benchmem -bench .; cd ../..
  - cd internal/dic; go test -tags=appengine -benchmem -bench .; cd ../..
  - /bin/sh ./go-coverall.sh

